export default {
  ADD: 'ADD',
  BUILD_OPERAND: 'BUILD_OPERAND',
  CLEAR: 'CLEAR',
  DIVIDE: 'DIVIDE',
  FLIP_SIGN: 'FLIP_SIGN',
  MULTIPLY: 'MULTIPLY',
  PERCENT: 'PERCENT',
  SOLVE: 'SOLVE',
  SUBTRACT: 'SUBTRACT'
}
